#pragma once

#define EM_TROUBLED "(>_<)"
#define EM_EMBARRASSED "(~_~;)"
#define EM_WINK "(^_-)"
#define EM_SCARED "(°_°)"
#define EM_JOYFUL "(^O^)"
#define EM_MIDDLEFINGER "(凸ಠ益ಠ)凸"
#define EM_SAD "(ToT)"
#define EM_SHAME "(-_-)"
#define EM_CONFUSED "(?_?)"
#define EM_EXCITED "＼(^o^)／"
#define EM_AMAZED "＼(◎o◎)／"
#define EM_HAPPY "(＾▽＾)"
#define EM_SURPRISED "(o.o)"
#define EM_TABLEFLIP "(╯°□°）╯︵ ┻━┻"
#define EM_DUNNO "¯\\(°_o)/¯"
#define EM_FIGHT "(ง •̀_•́)ง"
#define EM_THINKING "((⇀‸↼))"